default_platform(:ios)

platform :ios do
  desc "Build IPA archive for iOS"
  lane :build_ipa do
    setup_ci if ENV["CI"]

    build_app(
      workspace: "ios/UKPayCalc.xcworkspace",
      scheme: "UKPayCalc",
      export_method: "app-store",
      output_directory: "ios/build/output",
      output_name: "UKPayCalc.ipa"
    )
  end

  desc "Build and upload IPA to TestFlight"
  lane :beta do
    build_ipa
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
